### ISSUE TITLE
Jason thinks there should be a bustin bell sound

### ISSUE THREAD

**Issue by ROTARTSI82** [ROTARTSI82/VirtualBell#13]
title

Also he thinks the white on the customize schedule page is too jarring

Note: Kabir please dont close this

**Comment by chungderson** [comment]
yeah i also agree with Jason's Suggestion, make it at least at 150% volume

Note: Kabir please dont close this

**Comment by ROTARTSI82** [comment]
no andy stop

**Comment by CMEONE** [comment]
Alrighty I won't close it

**Comment by CMEONE** [comment]
Uh ok I'm going to close this now because it's been quite a few months...
