### ISSUE TITLE
Add option to open in popup

### ISSUE THREAD

**Issue by gadhagod** [ROTARTSI82/VirtualBell#14]
Hello @ROTARTSI82. This website is super cool and useful!
I was wondering if there was a way to have an option to have it open in a popup. I think that this might be better than having someone keep the tab open. 
I have implemented this change in my fork: https://github.com/gadhagod/VirtualBell. Right now it opens a popup right on opening the site, but I think it may be a good idea to allow other users to have the option of opening in a popup.
I am willing to work on this myself, if you are interested in adding this feature.

**Comment by CMEONE** [comment]
Hey @gadhagod,

Thanks so much for working on this! Maybe @ROTARTSI82 if you want to put a link to his repo, I don't know if we want to have this option mandatory for everyone, but if you want @gadhagod, you can add an option in settings and a conditional to check if users select a preference to have the popup (off by default to keep consistent behavior), then open a PR and I'll review it.

@ROTARTSI82 doesn't actively maintain this bell anymore (there used to be a redirect to my bell app which you already know of), but he may take a look :)

**Comment by gadhagod** [comment]
Hi @CMEONE.
Thanks for your response. By...
 > I don't know if we want to have this option mandatory for everyone

I don't quite understand what you mean. I agree that the option should not be mandatory, but rather an option.

**Comment by CMEONE** [comment]
Right yes, that is what I meant.

If I understand correctly, your fork opens in popup by default (mandatory). We would love to have this as an option, with the default being normal viewing and the popup as a toggle in settings. If you can add an option in `/settings.html` (probably a button, when clicked toggles between two options), store the preference in `localStorage`, and then use an if-statement in `index.html` to check whether to load the DOM or open a popup, then that would be great! Let us know when you have this working by opening a pull request.

Thanks so much!

**Comment by gadhagod** [comment]
Addressed in #15.
