### ISSUE TITLE
Desktop app version of VirtualBell

### ISSUE THREAD

**Issue by gadhagod** [ROTARTSI82/VirtualBell#17]
Hey,
I made a desktop app version of this app. Check it out here: https://github.com/gadhagod/VirtualBell-Desktop. It allows for a few more features and conveniences, which you can find on the README.
I was wondering if we could have this linked somewhere in the main bell. Let me know what you think.

**Comment by CMEONE** [comment]
Hmm... seems interesting... also, I'm wondering how it would be better as a desktop app vs PWA (progressive web app)?

**Comment by CMEONE** [comment]
I mean I'm sure that desktop app is great but PWA is much easier to implement imo. I'll take a look at the files and add a link if it works.

**Comment by gadhagod** [comment]
People can use this utility offline. They don't have to keep a tab open.

**Comment by CMEONE** [comment]
Also if it's a desktop app, we would probably want an exe for windows. For cross-platform compatibility pwa works best with a manifest and service worker, but dmg works fine. My only concern from a UX perspective is that users will need to right-click and open to bypass the restrictive security prompt and then accept the non-restrictive prompt.

**Comment by CMEONE** [comment]
Yes for PWA you can make it work offline without a tab with the use of service workers. For example, I made tApp.js (https://github.com/TogaTech/tApp/). I recommend doing a quick google search because service workers can be both very interesting and very annoying.

**Comment by gadhagod** [comment]
Agreed, but most people don't have service workers. I don't have a windows, so I can't test that the app built correctly. Maybe you can?

**Comment by CMEONE** [comment]
https://css-tricks.com/serviceworker-for-offline/ <= this is a good site to learn about service workers

**Comment by CMEONE** [comment]
BTW people don't actually need service workers to be installed, they are installed by the developer using `window.navigator` in the main js file and then can intercept all fetch requests, cache and return offline.

**Comment by gadhagod** [comment]
I can keep this project seperate and not affiliated with this on. Please let me know.

**Comment by CMEONE** [comment]
Then for PWA that will require a manifest.

Here is how the service worker is registered (can be done within `body`):
```
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/service-worker.js')
    .then(function(reg){
        console.log("Yes, it did.");
    }).catch(function(err) {
        console.log("No it didn't. This happened: ", err)
    });
}
```
The article I sent should guide you through how the service worker works and how to write it.

For an example of the manifest, see HarkerMSBell's `manifest.json` at https://utility.togatech.org/harkermsbell/manifest.json
Manifest is included in the `head` with `<link rel="manifest" href="manifest.json">`

**Comment by CMEONE** [comment]
I'll leave that decision to @ROTARTSI82 but I think for compatibility's sake, a PWA and service worker is better, doesn't require the app to be rebuilt after changes, works offline as an app on mobile and desktop, and no installation process with security prompts. For now, you can continue to develop your version but @ROTARTSI82 can decide whether to feature it on the bell.

**Comment by gadhagod** [comment]
I wasn't very familiar with service workers when developing this, and did not know you could run this webapp offline. Sound good.

**Comment by CMEONE** [comment]
I mean your dmg definitely looks great but I think it may be worthwhile to learn about PWAs and service workers for your sites in general. Good luck! :)

**Comment by gadhagod** [comment]
> I'll leave that decision to @ROTARTSI82 but I think for compatibility's sake, a PWA and service worker is better, doesn't require the app to be rebuilt after changes, works offline as an app on mobile and desktop, and no installation process with security prompts. For now, you can continue to develop your version but @ROTARTSI82 can decide whether to feature it on the bell.

No problem!

**Comment by CMEONE** [comment]
@gadhagod Right yea, I get it. Like I said, your app is really cool and I'll leave it to @ROTARTSI82 as the repo owner to decide whether to feature it as an announcement on the bell. I also think that you would probably benefit from learning about service workers and PWAs to make you a more well-rounded web developer is all. Anyways, good luck with your ventures :)

**Comment by gadhagod** [comment]
Thanks for your time!

**Comment by CMEONE** [comment]
No problem, feel free to let me know if you have any questions/concerns!
