### ISSUE TITLE
Not an issue but a suggestion 

### ISSUE THREAD

**Issue by ashwink2006** [ROTARTSI82/VirtualBell#2]
It would be cool if the highlight for the period was also a loading bar and moved as the period went along.

**Comment by CMEONE** [comment]
Ashwin,

I could code this on [HarkerMSBell](https://utility.togatech.org/harkermsbell/) as an optional feature if you are still interested.

Sincerely,
Kabir R.

**Comment by ROTARTSI82** [comment]
Kabir, this issue has been closed. This is the issue board for my bell, not yours. I'm locking this conversation.
