### ISSUE TITLE
https://andersonchungus.github.io/HarkerZoom/

### ISSUE THREAD

**Issue by andersonchungus** [ROTARTSI82/VirtualBell#3]
also, why is kabir's site exempt. you know what i mean, grant. 

Sincerely,
Andy

**Comment by ROTARTSI82** [comment]
i don't know what you mean.

**Comment by CMEONE** [comment]
Andy,

You know why. If you don't, just send me an email.

Also, your site is not exempt. Zoombombing is a serious issue. The document, my website, and Grant's bell are the only places allowed for Zoom links. I kindly request that you take down the website or redirect to one of the three approved places.

Sincerely,
Kabir R.

**Comment by ROTARTSI82** [comment]
This issue is extremely off topic. In the future, send andy an email instead of posting here.
