### ISSUE TITLE
Grammar counts!

### ISSUE THREAD

**Issue by MsWallaceHarker** [ROTARTSI82/VirtualBell#4]
Near the top of the bell schedule, which is by the way AWESOME!, you have a statement with a grammatical error in it: There is also now passing periods from free time to period 1!

It should either say, "There is also now a passing period from free time to period 1," or "There are also now passing periods from free time to period 1, as well as X to Y."

Thank you for bearing with an English teacher who likes official and public forms to have correct grammar. ~Ms. W

**Comment by ROTARTSI82** [comment]
Fixed! Thank you.

**Comment by andersonchungus** [comment]
xD nice
