### ISSUE TITLE
Unrelated issue but this seems to be an effective contact method

### ISSUE THREAD

**Issue by CMEONE** [ROTARTSI82/VirtualBell#6]
Could you explain this?

SGV5IHJpYmFrYSBuYXptYXJh4oCmIApLZWVwIGhhY2tlcm1hbmluZyAKUm90YXJ0c2kKClBzLiBwYXBlciBtYXJpbyBpcyBnb2QK

I found it in my yearbook and was wondering what cipher I could use to decode it. I know you wrote it because I can see the document history.

**Comment by andersonchungus** [comment]
xd kabir you're supposed to figure it out duh

**Comment by ROTARTSI82** [comment]
KABIR WHAT ARE YOU DOING THIS IS A FRICKING ISSUE TRACKER FOR MY BELL

**Comment by ROTARTSI82** [comment]
PLEASE STOP IT
